### ISSUE TITLE
Filenames in package.gz in telephony are wrong

### ISSUE THREAD

**Issue by Alex2610** [fexofenadine/brcm63xx-tch#3]
Hi, I've noticed that all the filenames contain /telephony on their name in packages.gz of telephony (in the cli I can clearly see the repetition of /telephony when trying to install for example asterisk11) please fix it, thanks

**Comment by fexofenadine** [comment]
Hey did the change fix it for you? I haven't resigned the Packages yet

**Comment by Alex2610** [comment]
Not properly, I own a dga4132, (agthp 2.2.1, openwrt 15.05.1) after trying to install asterisk18 (it seems to install it) but I receive some errors: 
```
/usr/sbin/asterisk: line 3: @: not found
/usr/sbin/asterisk: line 3: PPdtQ/lib/ld-uClibc.so.0W: not found
/usr/sbin/asterisk: line 3: : not found
/usr/sbin/asterisk: line 3: lA: not found
Q: not foundterisk: line 3: x
/usr/sbin/asterisk: line 3: ELFA4P4: not found
/usr/sbin/asterisk: line 4: pWR: not found
/usr/sbin/asterisk: line 2: syntax error: unexpected word (expecting ")")
```

**Comment by fexofenadine** [comment]
Yikes. I'm not sure I know how to fix that. Looks like a library dependency is missing, but I cant explain the character corruption either.  I don't have the source, so this might have to wait till someone else is able to fix it

**Comment by Alex2610** [comment]
Ok, thanks,
However on asterisk11 I get only
`/usr/sbin/asterisk: line *: syntax error: unexpected word (expecting ")")`
 I can't remember the actual line though 😂...

**Comment by fexofenadine** [comment]
Unfortunately I am not able to replicate the issue on my router either, both versions of asterisk are working fine on it :/

**Comment by Alex2610** [comment]
thanks the issue should be there 👍
